orders description and stats
Brimrix/abbs-poc pull request #58
Opened 2024-07-03 10:08 UTC by SalmanMughal789

I am excited to tell you that this pull request resolves the following issues of orders of invoice.

- The orders description is auto-generated
- 
- The orders description is editable
- 
- The Stats of totalAmount and totalArea of orders are displayed and updates in real time as the user changes anything of order items improving the overall user experience. 
- 
- The inputNumber bug is addressed. Price and quantity does not accept string and the controls to increase or decrease the value can be controlled by the buttons or from keyboard. 

- There is one generic method which updates the stats whenever any changes occurs in image-area-price-height-width-quantity  etc

Closed #53 
Closed #54 

@Waqar-SE Please review

2024-07-03 11:43 UTC, Waqar-SE requested changes

2024-07-03 11:43 UTC, Waqar-SE commented on frontend/context/BillContext.jsx
> +          else{
It's ambigious to handle orders when orderId is null/false, please change it.

2024-07-03 11:44 UTC, Waqar-SE commented on frontend/context/BillContext.jsx
> +          else{
If this is to cater description, please add a separate handler for description of order instead.

2024-07-03 21:10 UTC, Waqar-SE requested changes
Changes required. Also the order stats don't show up when we open an invoice in edit mode. Please fix that as well.

2024-07-03 21:10 UTC, Waqar-SE commented on frontend/context/BillContext.jsx
> +
We can't rely on updateRow function here as that reset the amount and area for Row which should not be updated when the description is changed. 

Instead change the description directly by doing something like 
`({ ...item, description: action.payload.description,state:'modified' })` in place of updateRow function call.

2024-07-03 21:10 UTC, Waqar-SE commented on frontend/context/BillContext.jsx
> +        else {
We don't need this else branch as this same case is handled in the first condition where you're checking for itemId and item model.

2024-07-03 21:10 UTC, Waqar-SE commented on frontend/components/invoices/Table.jsx
> +      render: (text, row) => isOrderRow(row) ? row.area ? row.area : 'Order Area' : Number(text).toFixed(2)
Don't fall back to "Order area" but show the area without checking if it's null or not. Currently it hides incorrect calculations. 

To make sure you don't show NAN of undefined you can do `row.area || 0'

2024-07-03 21:10 UTC, Waqar-SE commented on frontend/components/invoices/Table.jsx
> +      render: (value, row) => isOrderRow(row) ? row.amount? row.amount : 'Order Total' : Number(value?.toFixed(2))
Do the same thing here as order area cell.

2024-07-04 08:39 UTC, SalmanMughal789 commented
> Changes required. Also the order stats don't show up when we open an invoice in edit mode. Please fix that as well.

Its done

2024-07-04 10:21 UTC, Waqar-SE requested changes

2024-07-04 10:21 UTC, Waqar-SE commented on frontend/context/BillContext.jsx
> +    debugger;
Remove this statement.

2024-07-06 05:36 UTC, Waqar-SE approved these changes

2024-07-06 05:37 UTC, merged